lab6/lab6/Models/Room.cs
using Microsoft.SqlServer.Server;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using Proiect_web_final.Models.MyValidation;

namespace lab6.Models
{
    public class Room
    {
        public int RoomId { get; set; }

        //nr persoane validare
        [RegularExpression(@"^[1-9]$", ErrorMessage = "This is not a valid number, out of 1-9!")]
        [PrimeNumberValidator]
        public int NrPeople { get; set; }

        // one-to-many relationship
        public int RezervationId { get; set; }
        public virtual Rezervation Rezervation { get; set; }

        //one-to-many

        [ForeignKey("Furniture")]
        public int FurnitureId { get; set; }

        public virtual Furniture Furniture { get; set; }

        // many-to-many relationship
        public virtual ICollection<Utility> Utilities { get; set; }

        // dropdown lists
        public IEnumerable<SelectListItem> FurnitureList { get; set; }
        public IEnumerable<SelectListItem> RezervationList { get; set; }

        // checkboxes list
        [NotMapped]
        public List<CheckBoxViewModel> UtilitiesList { get; set; }

    }
    /*
    public class DbCtx : DbContext
    {
        public DbCtx() : base("DbConnectionString")
        {
            Database.SetInitializer<DbCtx>(new Initp());
        }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Furniture> Furnitures { get; set; }
    }
    
    public class Initp : DropCreateDatabaseIfModelChanges<DbCtx>
    {
        protected override void Seed(DbCtx ctx)
        {
            Furniture type1 = new Furniture { FurnitureId = 12, TypeFurniture = "Single" };
            Furniture type2 = new Furniture { FurnitureId = 13, TypeFurniture = "Double" };
            Furniture type3 = new Furniture { FurnitureId = 14, TypeFurniture = "Family" };
            ctx.Furnitures.Add(type1);
            ctx.Furnitures.Add(type2);
            ctx.Furnitures.Add(type3);
            ctx.Rooms.Add(new Room
            {
                NrPeople = 3,
                //Furniture = new Furniture { TypeFurniture = "fnrejgnerg"}
                FurnitureId = type1.FurnitureId
            });
            ctx.SaveChanges();
            base.Seed(ctx);
        }
    }
    */
}

lab6/lab6/Controllers/RoomController.cs
using lab6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using lab6.Models.MyDatabaseInitializer;


namespace lab6.Controllers
{
    public class RoomController : Controller
    {
        private DbCtx db = new DbCtx();

        [HttpGet]
        public ActionResult Index()
        {
            List<Room> rooms = db.Rooms.ToList();
            ViewBag.Rooms = rooms;
            return View();
        }


        public ActionResult Details(int? id)
        {
            if (id.HasValue)
            {
                Room room = db.Rooms.Find(id);
                if (room != null)
                {
                    return View(room);
                }
                return HttpNotFound("Couldn't find the room with id " + id.ToString() + "!");
            }
            return HttpNotFound("Missing room id parameter!");
        }


        [HttpGet]
        public ActionResult New()
        {
            Room room = new Room();
            room.FurnitureList = GetAllFurnitures();
            room.RezervationList = GetAllRezervations();
            room.UtilitiesList = GetAllUtilities();
            room.Utilities = new List<Utility>();
            return View(room);
        }

        [HttpPost]
        public ActionResult New(Room roomRequest)
        {
            roomRequest.FurnitureList = GetAllFurnitures();
            roomRequest.RezervationList = GetAllRezervations();

            // memoram intr-o lista doar genurile care au fost selectate
            var selectedUtilities = roomRequest.UtilitiesList.Where(b => b.Checked).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    roomRequest.Utilities = new List<Utility>();
                    for (int i = 0; i < selectedUtilities.Count(); i++)
                    {
                        // cartii pe care vrem sa o adaugam in baza de date ii 
                        // asignam genurile selectate 
                        Utility utility = db.Utilities.Find(selectedUtilities[i].Id);
                        roomRequest.Utilities.Add(utility);
                    }
                    db.Rooms.Add(roomRequest);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(roomRequest);
            }
            catch (Exception e)
            {
                var msg = e.Message;
                return View(roomRequest);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                Room room = db.Rooms.Find(id);
                room.FurnitureList = GetAllFurnitures();
                room.RezervationList = GetAllRezervations();
                room.UtilitiesList = GetAllUtilities();

                foreach (Utility checkedUtility in room.Utilities)
                {   // iteram prin genurile care erau atribuite cartii inainte de momentul accesarii formularului
                    // si le selectam/bifam  in lista de checkbox-uri
                    room.UtilitiesList.FirstOrDefault(g => g.Id == checkedUtility.UtilityId).Checked = true;
                }
                if (room == null)
                {
                    return HttpNotFound("Coludn't find the room with id " + id.ToString() + "!");
                }
                return View(room);
            }
            return HttpNotFound("Missing room id parameter!");
        }

        [HttpPut]
        public ActionResult Edit(int id, Room roomRequest)
        {
            roomRequest.FurnitureList = GetAllFurnitures();
            roomRequest.RezervationList = GetAllRezervations();

            // preluam cartea pe care vrem sa o modificam din baza de date
            Room room = db.Rooms.Include("Rezervation").Include("Furniture")
                        .SingleOrDefault(b => b.RoomId.Equals(id));

            // memoram intr-o lista doar genurile care au fost selectate din formular
            var selectedUtilities = roomRequest.UtilitiesList.Where(b => b.Checked).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    if (TryUpdateModel(room))
                    {
                        room.NrPeople = roomRequest.NrPeople;
                        room.RezervationId = roomRequest.RezervationId;
                        room.FurnitureId = roomRequest.FurnitureId;

                        room.Utilities.Clear();
                        room.Utilities = new List<Utility>();

                        for (int i = 0; i < selectedUtilities.Count(); i++)
                        {
                            // cartii pe care vrem sa o editam ii asignam genurile selectate 
                            Utility utility = db.Utilities.Find(selectedUtilities[i].Id);
                            room.Utilities.Add(utility);
                        }
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(roomRequest);
            }
            catch (Exception)
            {
                return View(roomRequest);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            Room room = db.Rooms.Find(id);
            if (room != null)
            {
                db.Rooms.Remove(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound("Couldn't find the room with id " + id.ToString() + "!");
        }

        [NonAction]
        public List<CheckBoxViewModel> GetAllUtilities()
        {
            var checkboxList = new List<CheckBoxViewModel>();
            foreach (var utility in db.Utilities.ToList())
            {
                checkboxList.Add(new CheckBoxViewModel
                {
                    Id = utility.UtilityId,
                    Name = utility.Name,
                    Checked = false
                });
            }
            return checkboxList;
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllFurnitures()
        {
            var selectList = new List<SelectListItem>();
            foreach (var cover in db.Furnitures.ToList())
            {
                selectList.Add(new SelectListItem
                {
                    Value = cover.FurnitureId.ToString(),
                    Text = cover.TypeFurniture
                });
            }
            return selectList;
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllRezervations()
        {
            var selectList = new List<SelectListItem>();
            foreach (var rezervation in db.Rezervations.ToList())
            {
                selectList.Add(new SelectListItem
                {
                    Value = rezervation.RezervationId.ToString(),
                    Text = rezervation.Name
                });
            }
            return selectList;
        }
    }
}

lab6/lab6/Controllers/UtilityController.cs
using lab6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using lab6.Models.MyDatabaseInitializer;

namespace lab6.Controllers
{
    public class UtilityController : Controller
    {
        private DbCtx db = new DbCtx();

        public ActionResult Index()
        {
            ViewBag.Utilities = db.Utilities.ToList();
            return View();
        }

        public ActionResult New()
        {
            Utility utility = new Utility();
            return View(utility);
        }

        [HttpPost]
        public ActionResult New(Utility roomTypeRequest)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Utilities.Add(roomTypeRequest);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(roomTypeRequest);
            }
            catch (Exception e)
            {
                return View(roomTypeRequest);
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                Utility utility = db.Utilities.Find(id);

                if (utility == null)
                {
                    return HttpNotFound("Couldn't find the utility type with id " + id.ToString() + "!");
                }
                return View(utility);
            }
            return HttpNotFound("Couldn't find the utility type with id " + id.ToString() + "!");
        }

        [HttpPut]
        public ActionResult Edit(int id, Utility furnitureRequestor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Utility furniture = db.Utilities.Find(id);
                    if (TryUpdateModel(furniture))
                    {
                        furniture.Name = furnitureRequestor.Name;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(furnitureRequestor);
            }
            catch (Exception e)
            {
                return View(furnitureRequestor);
            }
        }

        [HttpDelete]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                Utility furniture = db.Utilities.Find(id);
                if (furniture != null)
                {
                    db.Utilities.Remove(furniture);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return HttpNotFound("Couldn't find the utility type with id " + id.ToString() + "!");
            }
            return HttpNotFound("Utility type id parameter is missing!");
        }
    }
}

lab6/lab6/Views/Room/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

lab6/lab6/Views/Room/Details.cshtml
@model lab6.Models.Room

@{ ViewBag.Title = "Details"; }

<h2>@ViewBag.Title</h2>



@*
    @Html.Display("Author")
    @Html.DisplayFor(b => b.Author)*@

@if (Model.Rezervation != null)
{
@Html.Label("Rezervation", "Rezervation:")
                <br />
                                <p>@Model.Rezervation.Name</p>

                                                @Html.Label("Rezervation", "Person:")
                                                                <br />
                                                                                <p>@Model.Rezervation.Persone.PhoneNumber</p>}


@if (Model.NrPeople != 0)
{
@Html.LabelFor(b => b.NrPeople, "Number of Pages:")
                <p>@Model.NrPeople</p>}


@if (Model.Utilities.Count > 0)
{
@Html.Label("Utilities", "Utilities:")
                <br />
                                <ul>
                                    @foreach (var genre in Model.Utilities)
                                    {
                    <li>@genre.Name</li>}
                                </ul>}

@if (Model.Furniture != null)
{
@Html.Label("Furniture", "Furniture Type:")
                <br />
                                @Html.DisplayFor(b => b.Furniture.TypeFurniture)
                                                <br />
                                                                <br />}

@using (Html.BeginForm(actionName: "Edit", controllerName: "Room", method: FormMethod.Get, routeValues: new { id = Model.RoomId }))
{
<button style="margin-right:5px" class="btn btn-primary col-lg-1" type="submit">Update</button>}

@using (Html.BeginForm(actionName: "Delete", controllerName: "Room", method: FormMethod.Post, routeValues: new { id = Model.RoomId }))
{
@Html.HttpMethodOverride(HttpVerbs.Delete)
                <button style="margin-right:5px" class="btn btn-primary col-lg-1" type="submit">Delete</button>}

@using (Html.BeginForm(actionName: "Index", controllerName: "Furniture", method: FormMethod.Get))
{
<button style="margin-right:5px" class="btn btn-primary col-lg-1" type="submit">See furnitures</button>}

@using (Html.BeginForm(actionName: "Index", controllerName: "Rezervation", method: FormMethod.Get))
{
<button style="margin-right:5px" class="btn btn-primary col-lg-1" type="submit">See rezervations</button>}


<br />

lab6/lab6/Views/Room/Edit.cshtml
@model lab6.Models.Room
@{
    ViewBag.Title = "Update";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(actionName: "Edit", controllerName: "Room"))
{
    @Html.HttpMethodOverride(HttpVerbs.Put)

    @Html.HiddenFor(b => b.RoomId)
    <br />
    <br />

    

    @Html.Label("NrPeople", "Number of People:")
    <br />
    @Html.EditorFor(b => b.NrPeople, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(b => b.NrPeople, "", new { @class = "text-danger" })
    <br />


    @Html.Label("Furniture", "Furniture:")
    <br />
    @Html.DropDownListFor(b => b.FurnitureId, new SelectList(Model.FurnitureList, "Value", "Text"), "Choose a book type", new { @class = "form-control" })
    @Html.ValidationMessageFor(b => b.FurnitureId, "", new { @class = "text-danger" })
    <br />
    <br />

    @Html.Label("Rezervation", "Rezervation:")
    <br />
    @Html.DropDownListFor(b => b.RezervationId, new SelectList(Model.RezervationList, "Value", "Text"), "Choose a publisher", new { @class = "form-control" })
    @Html.ValidationMessageFor(b => b.RezervationId, "", new { @class = "text-danger" })
    <br />
    <br />

    @Html.LabelFor(b => b.UtilitiesList, "Choose utilities:")
    <br />
    for (int i = 0; i < Model.UtilitiesList.Count(); i++)
    {
        @Html.HiddenFor(b => b.UtilitiesList[i].Id)
        @Html.HiddenFor(b => b.UtilitiesList[i].Name)
        @Html.CheckBoxFor(b => b.UtilitiesList[i].Checked)
        @Html.DisplayFor(b => b.UtilitiesList[i].Name)
        <br />
    }
    <br />
    <button class="btn btn-primary" type="submit">Update</button>
}

lab6/lab6/Views/Room/Index.cshtml
@{
    ViewBag.Title = "Rooms";
}

<h2>@ViewBag.Title</h2>


@foreach (var room in ViewBag.Rooms)
{
    <div class="panel panel-default">
        <div class="panel-body">


            @Html.Label("NrPeople", "Number People:")
            <br />
            <p>@room.NrPeople</p>

            @using (Html.BeginForm(actionName: "Details", controllerName: "Room", method: FormMethod.Get,
            routeValues: new { id = room.RoomId }))
            {
                <button style="margin-right:5px" class="btn btn-primary col-lg-1" type="submit">Details</button>
            }
        </div>
    </div>
}

<div>
    @Html.ActionLink("Add room", "New")
</div>

<div>
    @Html.ActionLink("Add rezervation details", "New", "Rezervation")
</div>

<div>
    @Html.ActionLink("Add furniture type", "New", "Furniture")
</div>

<div>
    @Html.ActionLink("Add utility type", "New", "Utility")
</div>

lab6/lab6/Views/Room/New.cshtml
@model lab6.Models.Room
@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(actionName: "New", controllerName: "Room", method: FormMethod.Post))
{
    

    @Html.Label("NrPeople", "NrPeople:")
    <br />
    @Html.TextBoxFor(b => b.NrPeople, null, new { placeholder = "Type in the room's number of people", @class = "form-control", @type = "number" })
    @Html.ValidationMessageFor(b => b.NrPeople, "", new { @class = "text-danger" })
    <br />

  
    @Html.Label("Furniture", "Furniture:")
    <br />
    @Html.DropDownListFor(b => b.FurnitureId, new SelectList(Model.FurnitureList, "Value", "Text"), "Choose a furniture type", new { @class = "form-control" })
    @Html.ValidationMessageFor(b => b.FurnitureId, "", new { @class = "text-danger" })
    <br />
    <br />

    @Html.Label("Rezervation", "Rezervation:")
    <br />
    @Html.DropDownListFor(b => b.RezervationId, new SelectList(Model.RezervationList, "Value", "Text"), "Choose a rezervation", new { @class = "form-control" })
    @Html.ValidationMessageFor(b => b.RezervationId, "", new { @class = "text-danger" })
    <br />
    <br />

    @Html.LabelFor(b => b.UtilitiesList, "Choose utilities:")
    <br />
    for (int i = 0; i < Model.UtilitiesList.Count(); i++)
    {
        @Html.HiddenFor(b => b.UtilitiesList[i].Id)
        @Html.HiddenFor(b => b.UtilitiesList[i].Name)
        @Html.CheckBoxFor(b => b.UtilitiesList[i].Checked)
        @Html.DisplayFor(b => b.UtilitiesList[i].Name)
        <br />
    }
    @Html.ValidationMessageFor(b => b.UtilitiesList, null, new { @class = "text-danger" })

    <br />
    <button class="btn btn-primary" type="submit">Create</button>
}